package com.apple.webx.common.utill;

/**
 * 消息队列静态配置
 * 
 * @author Jndong
 *
 */
public class MessageQueueUtil {

	public enum COMMDITY_CRAWLING {
		CID_CRAWLING_COMMODITY,
		TOPIC_CRAWLING_COMMODITY,
		PID_CRAWLING_COMMODITY
	}
	
	//商品浏览记录
	public enum COMMODITY_RECENT_VIEW{
		TOPIC_COMMODITY_RECENT_VIEW,
		//PRODUCER
		PID_COMMODITY_RECENT_VIEW,
		//CONSUMER
		CID_COMMODITY_RECENT_VIEW
	}
	
	//商品添加
	public enum COMMODITY_ADD{
		TOPIC_COMMODITY_ADD,
		//PRODUCER
		PID_COMMODITY_ADD,
		//CONSUMER
		CID_COMMODITY_ADD
	}
	
	//商品描述修改(新增)
	public enum COMMODITY_DESCRIPTION_UPDATE{
		TOPIC_COMMODITY_DESCRIPTION_UPDATE,
		//PRODUCER
		PID_COMMODITY_DESCRIPTION_UPDATE,
		//CONSUMER
		CID_COMMODITY_DESCRIPTION_UPDATE
	}
	
	//商品更新
	public enum COMMODITY_UPDATE{
		TOPIC_COMMODITY_UPDATE,
		//PRODUCER
		PID_COMMODITY_UPDATE,
		//CONSUMER
		CID_COMMODITY_UPDATE
	}
	
	
	//商品下架
	public enum COMMODITY_RESELLER{
		TOPIC_COMMODITY_RESELLER,
		//PRODUCER
		PID_COMMODITY_RESELLER,
		//CONSUMER
		CID_COMMODITY_RESELLER
	}
	
	//基础类目修改
	public enum FOUNDATION_CATEGORY_UPDATE{
		TOPIC_FOUNDATION_CATEGORY_UPDATE,
		//PRODUCER
		PID_FOUNDATION_CATEGORY_UPDATE,
		//CONSUMER
		CID_FOUNDATION_CATEGORY_UPDATE
	}
	
	//店铺类目修改
	public enum SHOP_CATEGORY_UPDATE{
		TOPIC_SHOP_CATEGORY_UPDATE,
		//PRODUCER
		PID_SHOP_CATEGORY_UPDATE,
		//CONSUMER
		CID_SHOP_CATEGORY_UPDATE
	}
	
	//店铺类目新增
	public enum SHOP_CATEGORY_ADD{
		TOPIC_SHOP_CATEGORY_ADD,
		//PRODUCER
		PID_SHOP_CATEGORY_ADD,
		//CONSUMER
		CID_SHOP_CATEGORY_ADD
	}
	
	
	//店铺类目删除
	public enum SHOP_CATEGORY_DEL{
		TOPIC_SHOP_CATEGORY_DEL,
		//PRODUCER
		PID_SHOP_CATEGORY_DEL,
		//CONSUMER
		CID_SHOP_CATEGORY_DEL
	}
	
	
	//店铺公司信息修改
	public enum SHOP_COMPANY_DETAIL_UPDATE{
		TOPIC_SHOP_COMPANY_DETAIL_UPDATE,
		//PRODUCER
		PID_SHOP_COMPANY_DETAIL_UPDATE,
		//CONSUMER
		CID_SHOP_COMPANY_DETAIL_UPDATE
	}
	
	
	//打开恰恰
	public enum OPEN_CHAT{
		TOPIC_OPEN_CHAT,
		//PRODUCER
		PID_OPEN_CHAT,
		//CONSUMER
		CID_OPEN_CHAT
	}
	
}
