package com.apple.webx.domain;

public class Craw1688Test extends Craw1688TestKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.COMPANY_NAME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.FOUNDATION_TIME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String foundationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.REGISTER_PAY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String registerPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.BUSINESS_SCOPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.MAJOR_BUSSINESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String majorBussiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.IS_OEM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String isOem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.BUSINESS_MODEL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String businessModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.MOJOR_CLIENT
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String mojorClient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ANNUAL_TURNOVER
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String annualTurnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.MAJOR_MARKET
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String majorMarket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.BUSSINESS_ADDRESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String bussinessAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ANNUAL_EXPORTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String annualExports;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.EXPLOYEES_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String exployeesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ACTING_LEVEL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String actingLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.SERVICE_INDUSTRY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String serviceIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.PER_MONTH
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String perMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.PLANT_AREA
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String plantArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.PROCESS_METHOD
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String processMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.QUALITY_CERTIFICATION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String qualityCertification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.CRAFTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String crafts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ISO
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String iso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.SERVICE_SCOPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String serviceScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.CERTIFICATE_SOURCE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String certificateSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.COMPANY_INFO_URL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String companyInfoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.COMPANY_INDUCTION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String companyInduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.REGISTRATION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String registration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ESTABLISHED_DATE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String establishedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ENTERPRISE_TYPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String enterpriseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.REPRESENTATIVE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String representative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.BUSI_REGIS_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String busiRegisNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.DEVEL_PEO
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String develPeo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.SALE_AREA
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String saleArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.CUSUMER_GROUP
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String cusumerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.BRAND_NAME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.QUA_MAN_TYPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String quaManType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.BANK
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.BANK_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String bankNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.CONTACTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.TELEPHONE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ALI_TALK
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String aliTalk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.PHONE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.FAX
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ADRESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.SEARCH_CATEGORY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String searchCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ZIP
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.RESERVED_COL_1
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String reservedCol1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.RESERVED_COL_2
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String reservedCol2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.COMPANY_NAME
     *
     * @return the value of CRAW1688_TEST.COMPANY_NAME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.COMPANY_NAME
     *
     * @param companyName the value for CRAW1688_TEST.COMPANY_NAME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.FOUNDATION_TIME
     *
     * @return the value of CRAW1688_TEST.FOUNDATION_TIME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getFoundationTime() {
        return foundationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.FOUNDATION_TIME
     *
     * @param foundationTime the value for CRAW1688_TEST.FOUNDATION_TIME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setFoundationTime(String foundationTime) {
        this.foundationTime = foundationTime == null ? null : foundationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.REGISTER_PAY
     *
     * @return the value of CRAW1688_TEST.REGISTER_PAY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getRegisterPay() {
        return registerPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.REGISTER_PAY
     *
     * @param registerPay the value for CRAW1688_TEST.REGISTER_PAY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setRegisterPay(String registerPay) {
        this.registerPay = registerPay == null ? null : registerPay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.BUSINESS_SCOPE
     *
     * @return the value of CRAW1688_TEST.BUSINESS_SCOPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.BUSINESS_SCOPE
     *
     * @param businessScope the value for CRAW1688_TEST.BUSINESS_SCOPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.MAJOR_BUSSINESS
     *
     * @return the value of CRAW1688_TEST.MAJOR_BUSSINESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getMajorBussiness() {
        return majorBussiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.MAJOR_BUSSINESS
     *
     * @param majorBussiness the value for CRAW1688_TEST.MAJOR_BUSSINESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setMajorBussiness(String majorBussiness) {
        this.majorBussiness = majorBussiness == null ? null : majorBussiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.IS_OEM
     *
     * @return the value of CRAW1688_TEST.IS_OEM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getIsOem() {
        return isOem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.IS_OEM
     *
     * @param isOem the value for CRAW1688_TEST.IS_OEM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setIsOem(String isOem) {
        this.isOem = isOem == null ? null : isOem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.BUSINESS_MODEL
     *
     * @return the value of CRAW1688_TEST.BUSINESS_MODEL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getBusinessModel() {
        return businessModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.BUSINESS_MODEL
     *
     * @param businessModel the value for CRAW1688_TEST.BUSINESS_MODEL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setBusinessModel(String businessModel) {
        this.businessModel = businessModel == null ? null : businessModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.MOJOR_CLIENT
     *
     * @return the value of CRAW1688_TEST.MOJOR_CLIENT
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getMojorClient() {
        return mojorClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.MOJOR_CLIENT
     *
     * @param mojorClient the value for CRAW1688_TEST.MOJOR_CLIENT
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setMojorClient(String mojorClient) {
        this.mojorClient = mojorClient == null ? null : mojorClient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ANNUAL_TURNOVER
     *
     * @return the value of CRAW1688_TEST.ANNUAL_TURNOVER
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getAnnualTurnover() {
        return annualTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ANNUAL_TURNOVER
     *
     * @param annualTurnover the value for CRAW1688_TEST.ANNUAL_TURNOVER
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setAnnualTurnover(String annualTurnover) {
        this.annualTurnover = annualTurnover == null ? null : annualTurnover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.MAJOR_MARKET
     *
     * @return the value of CRAW1688_TEST.MAJOR_MARKET
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getMajorMarket() {
        return majorMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.MAJOR_MARKET
     *
     * @param majorMarket the value for CRAW1688_TEST.MAJOR_MARKET
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setMajorMarket(String majorMarket) {
        this.majorMarket = majorMarket == null ? null : majorMarket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.BUSSINESS_ADDRESS
     *
     * @return the value of CRAW1688_TEST.BUSSINESS_ADDRESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getBussinessAddress() {
        return bussinessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.BUSSINESS_ADDRESS
     *
     * @param bussinessAddress the value for CRAW1688_TEST.BUSSINESS_ADDRESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setBussinessAddress(String bussinessAddress) {
        this.bussinessAddress = bussinessAddress == null ? null : bussinessAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ANNUAL_EXPORTS
     *
     * @return the value of CRAW1688_TEST.ANNUAL_EXPORTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getAnnualExports() {
        return annualExports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ANNUAL_EXPORTS
     *
     * @param annualExports the value for CRAW1688_TEST.ANNUAL_EXPORTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setAnnualExports(String annualExports) {
        this.annualExports = annualExports == null ? null : annualExports.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.EXPLOYEES_NUM
     *
     * @return the value of CRAW1688_TEST.EXPLOYEES_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getExployeesNum() {
        return exployeesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.EXPLOYEES_NUM
     *
     * @param exployeesNum the value for CRAW1688_TEST.EXPLOYEES_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setExployeesNum(String exployeesNum) {
        this.exployeesNum = exployeesNum == null ? null : exployeesNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ACTING_LEVEL
     *
     * @return the value of CRAW1688_TEST.ACTING_LEVEL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getActingLevel() {
        return actingLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ACTING_LEVEL
     *
     * @param actingLevel the value for CRAW1688_TEST.ACTING_LEVEL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setActingLevel(String actingLevel) {
        this.actingLevel = actingLevel == null ? null : actingLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.SERVICE_INDUSTRY
     *
     * @return the value of CRAW1688_TEST.SERVICE_INDUSTRY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getServiceIndustry() {
        return serviceIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.SERVICE_INDUSTRY
     *
     * @param serviceIndustry the value for CRAW1688_TEST.SERVICE_INDUSTRY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setServiceIndustry(String serviceIndustry) {
        this.serviceIndustry = serviceIndustry == null ? null : serviceIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.PER_MONTH
     *
     * @return the value of CRAW1688_TEST.PER_MONTH
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getPerMonth() {
        return perMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.PER_MONTH
     *
     * @param perMonth the value for CRAW1688_TEST.PER_MONTH
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setPerMonth(String perMonth) {
        this.perMonth = perMonth == null ? null : perMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.PLANT_AREA
     *
     * @return the value of CRAW1688_TEST.PLANT_AREA
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getPlantArea() {
        return plantArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.PLANT_AREA
     *
     * @param plantArea the value for CRAW1688_TEST.PLANT_AREA
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setPlantArea(String plantArea) {
        this.plantArea = plantArea == null ? null : plantArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.PROCESS_METHOD
     *
     * @return the value of CRAW1688_TEST.PROCESS_METHOD
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getProcessMethod() {
        return processMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.PROCESS_METHOD
     *
     * @param processMethod the value for CRAW1688_TEST.PROCESS_METHOD
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setProcessMethod(String processMethod) {
        this.processMethod = processMethod == null ? null : processMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.QUALITY_CERTIFICATION
     *
     * @return the value of CRAW1688_TEST.QUALITY_CERTIFICATION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getQualityCertification() {
        return qualityCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.QUALITY_CERTIFICATION
     *
     * @param qualityCertification the value for CRAW1688_TEST.QUALITY_CERTIFICATION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setQualityCertification(String qualityCertification) {
        this.qualityCertification = qualityCertification == null ? null : qualityCertification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.CRAFTS
     *
     * @return the value of CRAW1688_TEST.CRAFTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getCrafts() {
        return crafts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.CRAFTS
     *
     * @param crafts the value for CRAW1688_TEST.CRAFTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setCrafts(String crafts) {
        this.crafts = crafts == null ? null : crafts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ISO
     *
     * @return the value of CRAW1688_TEST.ISO
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getIso() {
        return iso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ISO
     *
     * @param iso the value for CRAW1688_TEST.ISO
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setIso(String iso) {
        this.iso = iso == null ? null : iso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.SERVICE_SCOPE
     *
     * @return the value of CRAW1688_TEST.SERVICE_SCOPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getServiceScope() {
        return serviceScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.SERVICE_SCOPE
     *
     * @param serviceScope the value for CRAW1688_TEST.SERVICE_SCOPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setServiceScope(String serviceScope) {
        this.serviceScope = serviceScope == null ? null : serviceScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.CERTIFICATE_SOURCE
     *
     * @return the value of CRAW1688_TEST.CERTIFICATE_SOURCE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getCertificateSource() {
        return certificateSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.CERTIFICATE_SOURCE
     *
     * @param certificateSource the value for CRAW1688_TEST.CERTIFICATE_SOURCE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setCertificateSource(String certificateSource) {
        this.certificateSource = certificateSource == null ? null : certificateSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.COMPANY_INFO_URL
     *
     * @return the value of CRAW1688_TEST.COMPANY_INFO_URL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getCompanyInfoUrl() {
        return companyInfoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.COMPANY_INFO_URL
     *
     * @param companyInfoUrl the value for CRAW1688_TEST.COMPANY_INFO_URL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setCompanyInfoUrl(String companyInfoUrl) {
        this.companyInfoUrl = companyInfoUrl == null ? null : companyInfoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.COMPANY_INDUCTION
     *
     * @return the value of CRAW1688_TEST.COMPANY_INDUCTION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getCompanyInduction() {
        return companyInduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.COMPANY_INDUCTION
     *
     * @param companyInduction the value for CRAW1688_TEST.COMPANY_INDUCTION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setCompanyInduction(String companyInduction) {
        this.companyInduction = companyInduction == null ? null : companyInduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.REGISTRATION
     *
     * @return the value of CRAW1688_TEST.REGISTRATION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getRegistration() {
        return registration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.REGISTRATION
     *
     * @param registration the value for CRAW1688_TEST.REGISTRATION
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setRegistration(String registration) {
        this.registration = registration == null ? null : registration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ESTABLISHED_DATE
     *
     * @return the value of CRAW1688_TEST.ESTABLISHED_DATE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getEstablishedDate() {
        return establishedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ESTABLISHED_DATE
     *
     * @param establishedDate the value for CRAW1688_TEST.ESTABLISHED_DATE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setEstablishedDate(String establishedDate) {
        this.establishedDate = establishedDate == null ? null : establishedDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ENTERPRISE_TYPE
     *
     * @return the value of CRAW1688_TEST.ENTERPRISE_TYPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getEnterpriseType() {
        return enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ENTERPRISE_TYPE
     *
     * @param enterpriseType the value for CRAW1688_TEST.ENTERPRISE_TYPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setEnterpriseType(String enterpriseType) {
        this.enterpriseType = enterpriseType == null ? null : enterpriseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.REPRESENTATIVE
     *
     * @return the value of CRAW1688_TEST.REPRESENTATIVE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.REPRESENTATIVE
     *
     * @param representative the value for CRAW1688_TEST.REPRESENTATIVE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setRepresentative(String representative) {
        this.representative = representative == null ? null : representative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.BUSI_REGIS_NUM
     *
     * @return the value of CRAW1688_TEST.BUSI_REGIS_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getBusiRegisNum() {
        return busiRegisNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.BUSI_REGIS_NUM
     *
     * @param busiRegisNum the value for CRAW1688_TEST.BUSI_REGIS_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setBusiRegisNum(String busiRegisNum) {
        this.busiRegisNum = busiRegisNum == null ? null : busiRegisNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.DEVEL_PEO
     *
     * @return the value of CRAW1688_TEST.DEVEL_PEO
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getDevelPeo() {
        return develPeo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.DEVEL_PEO
     *
     * @param develPeo the value for CRAW1688_TEST.DEVEL_PEO
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setDevelPeo(String develPeo) {
        this.develPeo = develPeo == null ? null : develPeo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.SALE_AREA
     *
     * @return the value of CRAW1688_TEST.SALE_AREA
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getSaleArea() {
        return saleArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.SALE_AREA
     *
     * @param saleArea the value for CRAW1688_TEST.SALE_AREA
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setSaleArea(String saleArea) {
        this.saleArea = saleArea == null ? null : saleArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.CUSUMER_GROUP
     *
     * @return the value of CRAW1688_TEST.CUSUMER_GROUP
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getCusumerGroup() {
        return cusumerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.CUSUMER_GROUP
     *
     * @param cusumerGroup the value for CRAW1688_TEST.CUSUMER_GROUP
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setCusumerGroup(String cusumerGroup) {
        this.cusumerGroup = cusumerGroup == null ? null : cusumerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.BRAND_NAME
     *
     * @return the value of CRAW1688_TEST.BRAND_NAME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.BRAND_NAME
     *
     * @param brandName the value for CRAW1688_TEST.BRAND_NAME
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.QUA_MAN_TYPE
     *
     * @return the value of CRAW1688_TEST.QUA_MAN_TYPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getQuaManType() {
        return quaManType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.QUA_MAN_TYPE
     *
     * @param quaManType the value for CRAW1688_TEST.QUA_MAN_TYPE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setQuaManType(String quaManType) {
        this.quaManType = quaManType == null ? null : quaManType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.BANK
     *
     * @return the value of CRAW1688_TEST.BANK
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.BANK
     *
     * @param bank the value for CRAW1688_TEST.BANK
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.BANK_NUM
     *
     * @return the value of CRAW1688_TEST.BANK_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getBankNum() {
        return bankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.BANK_NUM
     *
     * @param bankNum the value for CRAW1688_TEST.BANK_NUM
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum == null ? null : bankNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.CONTACTS
     *
     * @return the value of CRAW1688_TEST.CONTACTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.CONTACTS
     *
     * @param contacts the value for CRAW1688_TEST.CONTACTS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.TELEPHONE
     *
     * @return the value of CRAW1688_TEST.TELEPHONE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.TELEPHONE
     *
     * @param telephone the value for CRAW1688_TEST.TELEPHONE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ALI_TALK
     *
     * @return the value of CRAW1688_TEST.ALI_TALK
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getAliTalk() {
        return aliTalk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ALI_TALK
     *
     * @param aliTalk the value for CRAW1688_TEST.ALI_TALK
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setAliTalk(String aliTalk) {
        this.aliTalk = aliTalk == null ? null : aliTalk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.PHONE
     *
     * @return the value of CRAW1688_TEST.PHONE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.PHONE
     *
     * @param phone the value for CRAW1688_TEST.PHONE
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.FAX
     *
     * @return the value of CRAW1688_TEST.FAX
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.FAX
     *
     * @param fax the value for CRAW1688_TEST.FAX
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ADRESS
     *
     * @return the value of CRAW1688_TEST.ADRESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ADRESS
     *
     * @param adress the value for CRAW1688_TEST.ADRESS
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.SEARCH_CATEGORY
     *
     * @return the value of CRAW1688_TEST.SEARCH_CATEGORY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getSearchCategory() {
        return searchCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.SEARCH_CATEGORY
     *
     * @param searchCategory the value for CRAW1688_TEST.SEARCH_CATEGORY
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setSearchCategory(String searchCategory) {
        this.searchCategory = searchCategory == null ? null : searchCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ZIP
     *
     * @return the value of CRAW1688_TEST.ZIP
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ZIP
     *
     * @param zip the value for CRAW1688_TEST.ZIP
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.RESERVED_COL_1
     *
     * @return the value of CRAW1688_TEST.RESERVED_COL_1
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getReservedCol1() {
        return reservedCol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.RESERVED_COL_1
     *
     * @param reservedCol1 the value for CRAW1688_TEST.RESERVED_COL_1
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setReservedCol1(String reservedCol1) {
        this.reservedCol1 = reservedCol1 == null ? null : reservedCol1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.RESERVED_COL_2
     *
     * @return the value of CRAW1688_TEST.RESERVED_COL_2
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getReservedCol2() {
        return reservedCol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.RESERVED_COL_2
     *
     * @param reservedCol2 the value for CRAW1688_TEST.RESERVED_COL_2
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setReservedCol2(String reservedCol2) {
        this.reservedCol2 = reservedCol2 == null ? null : reservedCol2.trim();
    }
}