package com.apple.webx.domain;

public class Craw1688TestKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.ID
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRAW1688_TEST.DOMAIN_URL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    private String domainUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.ID
     *
     * @return the value of CRAW1688_TEST.ID
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.ID
     *
     * @param id the value for CRAW1688_TEST.ID
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRAW1688_TEST.DOMAIN_URL
     *
     * @return the value of CRAW1688_TEST.DOMAIN_URL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public String getDomainUrl() {
        return domainUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRAW1688_TEST.DOMAIN_URL
     *
     * @param domainUrl the value for CRAW1688_TEST.DOMAIN_URL
     *
     * @mbggenerated Mon Jan 04 17:55:48 CST 2016
     */
    public void setDomainUrl(String domainUrl) {
        this.domainUrl = domainUrl == null ? null : domainUrl.trim();
    }
}